### ISSUE TITLE
Error when updating Account

### ISSUE THREAD

**Issue by zhangwei1979** [moqui/mantle-usl#68]
To Reproduce

1. Go to Application -> My Account -> User ->Account
2. Leave Email Address not empty
3. Click Save

You will get the error “Field cannot be empty (for field contactMechId)”.

It is caused by the parameter contactMechId is changed to required in update#PartyContactOther in https://github.com/moqui/mantle-usl/commit/ce438c46aae64feb5116acd3462b0535e7769d15

**Comment by jonesde** [comment]
This is fixed in commit #1bc1775 along with a new replaceByPurpose option for ContactServices.store#PartyContactInfo.

Thank you for reporting this, you caught me in the middle of changing update#PartyContactOther to work like the TelecomNumber and PostalAddress update service but before adding this option to store#PartyContactInfo, and I had forgotten this update service was used there.
